redis:
  image: redis:latest
  ports:
     - 6379:6379/tcp

mailcatcher:
  image: schickling/mailcatcher
  ports:
     - 1025:1025/tcp
     - 1080:1080/tcp

local:
  restart: always
  build: .
  command: ["./wait-for-it.sh", "redis:6379", "--", "python", "manage.py", 'runserver', '0.0.0.0:8000']
  volumes:
    - .:/usr/src/app
  ports:
    - 8000:8000
  environment:
    - REDIS_URI=redis://redis:6379/
    - REDIS_DB=1
    - SMTP_HOST=mailserver
    - SMTP_PORT=1025
    - PYTHON_ENV=development
    - STRIPE_API_KEY=sk_test_BQokikJOvBiI2HlWgH4olfQ2
  links:
    - redis:redis

test:
  build: .
  command: ["./wait-for-it.sh", "redis:6379", "--", "python", "-m", "unittest", "discover", "test"]
  volumes:
    - .:/usr/src/app
  ports:
    - 5001:8000
  environment:
    - REDIS_URI=redis://redis:6379
    - REDIS_DB=1
    - STRIPE_API_KEY=sk_test_BQokikJOvBiI2HlWgH4olfQ2
  links:
    - redis:redis
